# Import Packages

In [1]:
import numpy as np
import pandas as pd

# Kumpulan Matrix

## Ruas kiri dan kanan jadi 1 matrix

In [ ]:
# 3x + y - z = 5
# 4x + 7z - 3z = 20
# 2x -2y + 5z = 10

matrix = np.array([[3.,  1., -1.,  5.],
                   [4.,  7., -3., 20.],
                   [2., -2.,  5., 10.]])

# hasil = [1.5060241  3.13253012 2.65060241]

In [ ]:
matrix = np.array([[ 1., 1.,  1.,  1., 13.],
                   [ 2., 3.,  0., -1.,  1.],
                   [-3., 4.,  1.,  2., 10.],
                   [ 1., 2., -1.,  1.,  1.]])

# hasil = [2.11111111 0.37037037 6.18518519 4.33333333]

## Ruas kiri matrix A, ruas kanan matrix B

In [ ]:
A = np.array([[3., 1., -1.],
              [4., 7., -3.],
              [2., -2., 5.]])

B = np.array([[ 5.], 
              [20.], 
              [10.]])

# hasil = [1.5060241  3.13253012 2.65060241]

In [ ]:
# |   1   1   1   1 | | x |   | 13 |
# |   2   3   0  -1 | | y | = |  1 |
# |  -3   4   1   2 | | z |   | 10 |
# |   1   2  -1   1 | | w |   |  1 |

A = np.array([[ 1.,  1.,  1.,  1.],
              [ 2.,  3.,  0., -1.],
              [-3., 4.,  1.,  2.],
              [ 1.,  2., -1.,  1.]])

B = np.array([[13.],
              [ 1.],
              [10.],
              [ 1.]])

# hasil = [2.11111111 0.37037037 6.18518519 4.33333333]

# Numpy Method `np.linalg.solve(a, b)`

In [3]:
# cara magic
# https://radiokuantum.wordpress.com/2018/03/22/menyelesaikan-persamaan-linear-multi-variabel-dengan-menggunakan-python-dan-numpy/

# |   1   1   1   1 | | x |   | 13 |
# |   2   3   0  -1 | | y | = |  1 |
# |  -3   4   1   2 | | z |   | 10 |
# |   1   2  -1   1 | | w |   |  1 |

A = np.array([[1, 1, 1, 1],
              [2, 3, 0, -1],
              [-3, 4, 1, 2],
              [1, 2, -1, 1]])

B = np.array([13, 1, 10, 1])

x = np.linalg.solve(A, B)
print(x)

[2.11111111 0.37037037 6.18518519 4.33333333]


# Metode dari Materi

## Gauss

In [80]:
matrix = np.array([[3,  1, -1,  5],
                   [4,  7, -3, 20],
                   [2, -2,  5, 10]], dtype="float32")

size = matrix[:, 0].size

resultMatrix = matrix.copy()

for i in range(1, size):
    print("step", i, "\n")
    rowBefore = resultMatrix[i-1]/resultMatrix[i-1, i-1] # depannya 1
    
    for j in range(i, size):
        resultMatrix[j] -= (rowBefore*resultMatrix[j, i-1])
        
        print(resultMatrix, "\n")
        

print("result matrix", resultMatrix, sep="\n\n")

step 1 

[[ 3.         1.        -1.         5.       ]
 [ 0.         5.6666665 -1.6666666 13.333334 ]
 [ 2.        -2.         5.        10.       ]] 

[[ 3.         1.        -1.         5.       ]
 [ 0.         5.6666665 -1.6666666 13.333334 ]
 [ 0.        -2.6666667  5.6666665  6.666667 ]] 

step 2 

[[ 3.         1.        -1.         5.       ]
 [ 0.         5.6666665 -1.6666666 13.333334 ]
 [ 0.         0.         4.882353  12.941177 ]] 

result matrix

[[ 3.         1.        -1.         5.       ]
 [ 0.         5.6666665 -1.6666666 13.333334 ]
 [ 0.         0.         4.882353  12.941177 ]]


## Eliminasi Gauss-Jordan

In [79]:
matrix = np.array([[3., 1., -1., 5.],
                   [4., 7., -3., 20.],
                   [2., -2., 5., 10.]])

size = matrix[:, 0].size

resultMatrix = matrix.copy()

for i in range(0, size):
    # i sebagai row pada tiap step
    print("step", i, "\n")
    resultMatrix[i] /= resultMatrix[i, i]
    
    for j in range(0, size):
        if i == j:
            continue
        resultMatrix[j] -= resultMatrix[i] * resultMatrix[j, i]
        print(resultMatrix, "\n")
        

result = resultMatrix[:, size].copy()
print("result", result, sep="\n")

step 0 

[[ 1.          0.33333333 -0.33333333  1.66666667]
 [ 0.          5.66666667 -1.66666667 13.33333333]
 [ 2.         -2.          5.         10.        ]] 

[[ 1.          0.33333333 -0.33333333  1.66666667]
 [ 0.          5.66666667 -1.66666667 13.33333333]
 [ 0.         -2.66666667  5.66666667  6.66666667]] 

step 1 

[[ 1.          0.         -0.23529412  0.88235294]
 [ 0.          1.         -0.29411765  2.35294118]
 [ 0.         -2.66666667  5.66666667  6.66666667]] 

[[ 1.          0.         -0.23529412  0.88235294]
 [ 0.          1.         -0.29411765  2.35294118]
 [ 0.          0.          4.88235294 12.94117647]] 

step 2 

[[ 1.          0.          0.          1.5060241 ]
 [ 0.          1.         -0.29411765  2.35294118]
 [ 0.          0.          1.          2.65060241]] 

[[1.         0.         0.         1.5060241 ]
 [0.         1.         0.         3.13253012]
 [0.         0.         1.         2.65060241]] 

result
[1.5060241  3.13253012 2.65060241]
