# Import Packages

In [11]:
import numpy as np
import pandas as pd

# Numpy Methods

## `np.linalg.solve(A, B)`

In [12]:
# AX = B
A = np.array([[1, 1, 1, 1],
              [2, 3, 0, -1],
              [-3, 4, 1, 2],
              [1, 2, -1, 1]], dtype="float32")

B = np.array([13, 1, 10, 1], dtype="float32")

X = np.linalg.solve(A, B)
print(x)

[2.1111112  0.37037036 6.185185   4.3333335 ]


## `np.linalg.inv(A)`

In [13]:
A = np.array([[1, 1, 1, 1],
              [2, 3, 0, -1],
              [-3, 4, 1, 2],
              [1, 2, -1, 1]])

A_invers = np.linalg.inv(A)
print(A_invers)

[[ 0.27777778  0.05555556 -0.16666667  0.11111111]
 [-0.07407407  0.18518519  0.11111111  0.03703704]
 [ 0.46296296  0.09259259  0.05555556 -0.48148148]
 [ 0.33333333 -0.33333333  0.          0.33333333]]


# Metode dari Materi

## Eliminasi Gauss

In [25]:
def Gauss(A, B, printStep=True):
    size = B.size
    matrix = np.concatenate((A, B.reshape(size, 1)), axis=1)
    
    for i in range(1, size):
        if printStep:
            print("step", i, "\n")
            
        rowBefore = matrix[i-1]/matrix[i-1, i-1] # depannya 1

        for j in range(i, size):
            matrix[j] -= (rowBefore*matrix[j, i-1])
            if printStep:
                print(matrix, "\n")
    
    return matrix

## Eliminasi Gauss-Jordan

### Dari Awal

In [35]:
def GaussJordan(A, B, printStep=False, showInv=False, showB=True):
    size = B.size
    matrix = A
    if showB:
        matrix = np.concatenate((A, B.reshape(size, 1)), axis=1)
    if showInv:
        identity = np.identity(size, dtype="float32")
        matrix = np.concatenate((matrix, identity), axis=1)
    
    for i in range(0, size):
        if printStep:
            print("step", i, "\n")
            
        matrix[i] /= matrix[i, i]

        for j in range(0, size):
            if i == j:
                continue
                
            matrix[j] -= matrix[i] * matrix[j, i]
            if printStep:
                print(matrix, "\n")
        
    return matrix

### Lanjutan Eliminasi Gauss

In [43]:
def GaussJordan2(A, B, printStep=False, showInv=False, showB=True):
    size = B.size
    matrix = A
    if showB:
        matrix = np.concatenate((A, B.reshape(size, 1)), axis=1)
    if showInv:
        identity = np.identity(size, dtype="float32")
        matrix = np.concatenate((matrix, identity), axis=1)

    for i in range(1, size):
        if printStep:
            print("step", i, "\n")
            
        rowBefore = matrix[i-1]/matrix[i-1, i-1]  # depannya 1

        for j in range(i, size):
            matrix[j] -= (rowBefore*matrix[j, i-1])
            if printStep:
                print(matrix, "\n")
            
    return matrix

## Iterasi - Jacobi

In [108]:
# AX = B
def Jacobi(A, B, X_before, es=0.005, printStep=False, iter=1, table={}):
    size = B.size
    X = np.zeros(size)
    RAE = np.zeros(size)

    # iterasi X -> x1, x2, x3, dst... || x, y, z, dst...
    for i in range(0, size):
        X[i] = B[i]
        for j in range(0, size):
            if i != j:
                X[i] -= A[i][j]*X_before[j]
        X[i] /= A[i, i]

    if printStep:
        print("\niter", iter)
        print(X)

    for i in range(0, size):
        RAE[i] = abs((X[i] - X_before[i])/X[i])

    if np.all(RAE < es) and iter < 100:
        return X

    return Jacobi(A, B, X, es, iter=iter+1, table=table)

# Driver Code

- **Gauss**
  ```py
  result = Gauss(A, B, printStep=False)
  ```

- **Gauss Jordan (dari awal)** | urutan: A B A_inv
  ```py
  result = GaussJordan(A, B, printStep=False, showInv=False, showB=True)
  ```

- **Gauss Jordan (lanjutan gauss)** | urutan A B A_inv | belum jadi
  ```py
  result = GaussJordan2(A, B, printStep=False, showInv=False, showB=True)
  ```
  
- **Jacobi**
  ```py
  # terkaan awal
  X0 = np.array([0, 0, 0], dtype="float32")
  result = Jacobi(A, B, X0, es=0.005, printStep=False)
  ```

In [111]:
A = np.array([[3,  1, -1],
              [4,  7, -3],
              [2, -2,  5]], dtype="float32")

B = np.array([5, 20, 10], dtype="float32")

X0 = np.array([0, 0, 0], dtype="float32")
result = Jacobi(A, B, X0, es=0.005, printStep=False)
print(result)

[1.50375578 3.12827236 2.64995906]
[[1.        0.        0.        1.506024 ]
 [0.        1.        0.        3.1325302]
 [0.        0.        1.        2.6506026]]
